### ISSUE TITLE
enable the addition of listeners/notifications on value changes to update other elements of a GUI

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [FancyJavaStuff/TransferGrid#3]

**Comment by tiggerbiggo** [comment]
Possibility of extending this by adding an interface, something along the lines of Updateable, with a method onUpdate, called on the object whenever the GUI is updated. Should just be able to check if the object implements this interface, and calling that method inside whatever listener will be added. I attempted this myself but I don't know enough about javafx to know which listener to add, and I don't know enough about how your code works to add the listener myself.

**Comment by RicardoMonteiroSimoes** [comment]
Added 2 new Interfaces in the new release for this.
